### ISSUE TITLE
Create new key import wizard

### ISSUE THREAD

**Issue by olabini** [twstrike/Enigmail#13]

**Comment by tcz001** [comment]
now key trust/key signing are in two dialogs which are independent, we are planning to merge the Key trust dialog into Key signing for the first change

**Comment by olabini** [comment]
Old description: improve and/or merge key import/key trust/key signing dialogs

**Comment by tcz001** [comment]
[link to thread](https://lists.enigmail.net/pipermail/enigmail-users_enigmail.net/2015-May/003016.html)

**Comment by olabini** [comment]
Based on input from the Enigmail developers, what they really want is a wizard that allows importing of of keys:
- You choose a file or something else to import
- You get a list of the keys that will be imported from that file (BEFORE importing)
- You can choose how much you trust the owner of that key
- Finally you get the choice to "share" your trust with the world

**Comment by olabini** [comment]
We should start by doing a mockup of this flow

**Comment by olabini** [comment]
Once we have something we can send it to the list for thoughts

**Comment by tcz001** [comment]
[mockups](https://moqups.com/fan.torchz@gmail.com/zvswRvFl/)
